<?php
/**
 * Main theme layout file.
 *
 * @package    Joomla.PullTester
 *
 * @copyright  Copyright (C) 2012 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>Requests - Joomla Pull Request Tester</title>
	<link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="/css/bootstrap.extended.css" rel="stylesheet" type="text/css" />
	<link href="/css/theme.css" rel="stylesheet" type="text/css" />
	<link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="/ico/favicon.ico">
	<link rel="apple-touch-icon" href="/ico/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/ico/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/ico/apple-touch-icon-114x114.png">
</head>
<body id="top">
<!-- Header -->
<div class="header">
	<div class="header-inner">
		<div class="container">
			<a class="brand pull-left" href="../index.html">
				<img src="/img/joomla.png" alt="Joomla" />
			</a>
			<a class="tip-small" href="#" rel="popover" data-original-title="Site Logo" data-placement="right">
				<i class="icon-info-sign"></i>
			</a>
			<ul class="nav nav-pills pull-right">
				<li>
					<a class="tip-small" href="#" rel="popover" data-original-title="Main Navigation" data-placement="left">
						<i class="icon-info-sign"></i>
					</a>
				</li>
				<li class="active"><a href="/">Home</a></li>
				<li class=""><a href="https://github.com/joomla/joomla-platform">GitHub</a></li>
				<li class=""><a href="http://developer.joomla.org">Developer Network</a></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Examples <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class=""><a href="../blog/index.html">Blog</a></li>
						<li class=""><a href="../community/index.html">Community</a></li>
						<li class=""><a href="../gallery/index.html">Gallery</a></li>
						<li class=""><a href="../shop/index.html">Shop</a></li>
						<li class=""><a href="../events/index.html">Events</a></li>
					</ul>
				</li>
			</ul>
			<!--/.nav-collapse -->
		</div>
	</div>
</div>
<!-- Container -->
<div class="container">
	<?php if ($this->buffer->exists('page.header')) :?>
	<div class="page-header">
		<?php echo $this->buffer->get('page.header'); ?>
	</div>
	<?php endif; ?>

	<?php echo $this->buffer->get('page.body'); ?>

	<hr />
	<div class="footer">
		<p class="pull-right"><a href="#top" id="back-top">Back to top</a></p>
		<p>&copy; Copyright OpenSourceMatters, Inc. 2012, All rights reserved.</p>
	</div>
</div>
<!-- Image Zoom Modal -->
<div class="modal fade" id="image-modal">
	<div class="modal-header"> <a class="close" data-dismiss="modal">×</a>
		<h3>Thumbnail Caption</h3>
	</div>
	<div class="modal-body">
		<p><img src="http://placehold.it/530x397" alt=""></p>
		<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	</div>
	<div class="modal-footer"><a href="#" class="btn" data-dismiss="modal">Close</a> </div>
</div>
<!-- Le javascript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-1.7.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script type="text/javascript">
	$('.dropdown-toggle').dropdown()
	$('#myModal').modal('hide')
	$('.typeahead').typeahead()
	$('.tabs').button()
	$('.tip').popover('hide')
	$('.tip-small').tooltip('hide')
	$(".alert-message").alert()
	$(window).bind("load resize", function() {
		var windowHeight = "height:"+($(window).height()-45)+"px"; // height of full document
		var windowWidth = "width:"+($(window).width()-30)+"px"; // width of full document
		$('.side-nav, .fluid-content.main, .modal.full').attr('style', windowHeight);
	});
	$(document).ready(function() {
		$(".tip-small").hide();
        $(".tip-hide").click(function(){
           $(".tip-small").toggle();
        });
	});
</script>
</body>
</html>
